package com.clinica.model;

public enum PatologiaAssociadaEnum {
    DIABETES, GASTRITE, DISLIPIDEMIA, DOENCA_RENAL_CRONICA, 
    DOENCAS_RESPIRATORIAS, HIPOTIREOIDISMO, DEPRESSAO, 
    TRANSTORNOS_ALIMENTARES, HIPERTENSAO, TRIGLICERIDES, 
    COLITE, DOENCAS_CARDIOVASCULARES, PROBLEMAS_CIRCULACAO, 
    HIPERTIREOIDISMO, ANSIEDADE, OUTROS;
}